name: cube_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.0
  bot_toast: ^4.1.3
  flutter_dotenv: ^5.2.1
  easy_localization: ^3.0.7
  get_it: ^8.0.2
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.0
  flutter_svg: ^2.0.15
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  restart: ^1.0.0+1
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  icons_launcher: ^3.0.0
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/i18n/
    - .env